### ISSUE TITLE
can not view the demo

### ISSUE THREAD

**Issue by kropple** [Permissionless-Software-Foundation/gatsby-ipfs-web-wallet#17]
hi.

id love to see the demo here
https://gateway.ipfs.io/ipfs/Qmbpb61YRhgdN7DpD7QLDxUpSYzwKbTppm6T2oUjPTy1X2
but there is no index.html or anything the browser accepts to run.

thank

**Comment by christroutner** [comment]
This will be implemented in a future PR. We have to have the app monitor the publishing address so that it can update it's IPFS hash on the front end.

**Comment by kropple** [comment]
cool thanks for answering.
is there any running version of this wallet online somewhere?
im looking for a minimal SLP wallet to onboard new people to BCH
i wanna hand them the wallet URL and a pre-filled WIF key, so they can quickly start using

**Comment by christroutner** [comment]
We're rolling out features as fast as we can to the open alpha release at
wallet.fullstack.cash.

mint.bitcoin.com is the next closest web wallet. If you're looking for a
mobile wallet, the Bitcoin.com wallet is pretty good.

**Comment by kropple** [comment]
wow this is gonna be good. just what i was looking for!

importing has 2 fields, mnemonic & wif. but it seems only taking mnemonic,, ignoring wif.
wif alone wont work.

nice would be a field which accepts wif or mnemonic and decides itself what it is, wif or mnemonic

**Comment by christroutner** [comment]
If you'd like to chat about the PSF and the software we use, or why we made
decisions about the software, or where its at and where it's heading, you
should join our Telegram group:

https://t.me/permissionless_software

**Comment by christroutner** [comment]
The IPFS link in the footer of [wallet.fullstack.cash](https://wallet.fullstack.cash) now automatically updates to reflect the current IPFS hash to access the site.

The current IPFS hash can also be found by looking at this address on a block explorer:
bitcoincash:qq8mk8etntclfdkny2aknh4ylc0uaewalszh5eytnr

Or accessing the memo.cash page for it:
https://memo.cash/profile/bitcoincash:qq8mk8etntclfdkny2aknh4ylc0uaewalszh5eytnr
